theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "dark"   # "default"  "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-include-cache
logo: "/assests/images/boku7.png"
search: true
