remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "dark"   # "default"  "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
    #  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
logo: "/assets/images/masthead.png"
masthead_title: "HomePage"
search: true
# Site Author
author:
  name: "Bobby Cooke"
  avatar: "/assets/images/bc-profile.jpg"
  bio: "xDev•malDev"
  location: "West Coast"
  links:
    - label: "HomePage"
      url: "https://0xboku.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/boku7"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0xBoku"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/bobby-cooke/"
teaser: assets/images/slae32-teaser.png

# Google Analytics
google_analytics: G-8ZGTLNXWYL

#Site Settings
locale: "en-US"
title: "Boku"
title_separator: "-"
name: "Boku"
description: "Pentesting & Exploit Dev"
url: "https://0xboku.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "boku7/boku7.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
breadcrumbs: false # true, false (default)
words_per_minute: 120


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
    #  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
