# Site Author
author:
  name             : "boku7"
  avatar           : "/BOKU.png"
  bio              : "OSCP | OSWP | CCNA"
  location         : "West Coast"
# theme                  : "minimal-mistakes-jekyll"
remote_theme             : "mmistakes/minimal-mistakes@4.15.1"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
enable_coderay: false
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
